// <auto-generated />
namespace MVCFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updb4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updb4));
        
        string IMigrationMetadata.Id
        {
            get { return "201710231611421_Updb4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
